- id: php-lint-all
  name: PHP Syntax Check (Comprehensive)
  description: Check PHP Syntax on ALL PHP staged files with user friendly messages and colors
  entry: pre_commit_hooks/php-lint.sh
  language: script
  files: \.php$
  args: [-s all]

- id: php-lint
  name: PHP Syntax Check (Quick)
  description: Runs php -l on all staged files. Exits when it hits the first errored file
  entry: php -l
  language: system
  files: \.php$

- id: php-unit
  name: PHP Unit
  description: Run the full php unit test. Checks which PHPUnit executable is available first and then runs it. Preference order is vendor/bin, phpunit and phpunit.phar.
  entry: pre_commit_hooks/php-unit.sh
  language: script
  files: \.php$

- id: php-pest
  name: PestPHP
  description: Run the full php unit test with PestPHP.
  entry: pre_commit_hooks/php-pest.sh
  language: script
  pass_filenames: false
  args: [--parallel]
  always_run: true

- id: php-pest-coverage
  name: PestPHP Coverage
  description: Run the full php unit test with PestPHP with coverage.
  entry: pre_commit_hooks/php-pest.sh
  language: script
  pass_filenames: false
  args: [--parallel --coverage --min=100]
  always_run: true

- id: php-stan
  name: PHPStan
  description: Check for bugs in your code using PHPStan.
  entry: pre_commit_hooks/php-stan.sh
  language: script
  files: \.php$
  always_run: true

- id: php-cs
  name: PHP Codesniffer
  description: Run php codesniffer against all staged files.
  entry: pre_commit_hooks/php-cs.sh
  language: script
  files: \.php$

- id: php-cbf
  name: PHP Codesniffer (Code Beutifier and Formatter)
  description: Run php codesniffer against all staged files.
  entry: pre_commit_hooks/php-cbf.sh
  language: script
  files: \.php$

- id: php-cs-fixer
  name: PHP Coding Standards Fixer
  description: Run php coding standards fixer against all staged files.
  entry: pre_commit_hooks/php-cs-fixer.sh
  language: script
  files: \.php$

- id: laravel-pint
  name: PHP Coding Standards Fixer
  description: Run php coding standards fixer against all staged files.
  entry: pre_commit_hooks/laravel-pint.sh
  language: script
  files: \.php$
  always_run: true
